name: Slack PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$GITHUB_PR_URL"'"}' $SLACK_WEBHOOK_URL
        env:
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
